---
title: "Team 3 R Notebook"
output: html_notebook
---

```{r load-packages, message = FALSE}
install.packages("reshape2")
library(knitr)
library(tidyverse)
library(broom)
library(htmltools)
library(ggplot2)
library(dplyr)
library(grid)
library(gridExtra)
library(reshape2)
```

```{r, ref.label=knitr::all_labels(), echo=TRUE, eval=FALSE}
data <- read.csv("/Users/inbalkatav/Desktop/לימודים/שנה ב סמסטר ד/מבוא לניתוח נתונים/Parental effects on childs self esteem.csv", check.names = FALSE)
names(data) <- gsub(" ", "_", names(data))

original_column_names <- names(data)
empty_columns <- which(original_column_names == "")
if(length(empty_columns) > 0) {
  names(data)[empty_columns] <- paste0("empty_column_", seq_along(empty_columns))
}
data <- subset(data, select = -c(Email_Address))
data <- data %>%
  rename(
    Gender = 'Select_your_gender',
    AgeGroup = 'Select_your_age_group:',
    AvoidsNewExperiences = 'you_love_to_try_new_things_or_come_out_of_your_comfort_zone_easily:',
    LacksSelfConfidence = 'you_consider_yourself_confident.',
    LackControlLife = 'how_much_do_you_consider,_you_have_control_on_your_life?_',
    SelfComparison = 'you_compare_yourself_to_others',
    SelfDoubt = 'how_often_you_self_doubt_yourself',
    TroubleInFeedbackReception = 'do_you_have_trouble_accepting_positive_feedback_or_criticism?',
    FearOfFailure = 'do_you_have_fear_of_failure?',
    PleaseOthers = 'you_always_try_to_please_others',
    HesitantShareMistakes = 'Do_you_feel_confident_to_share_your_mistakes_with_your_parents_?',
    ParentsSociallyChallenged = 'How_your_parents_are_in_public_gatherings?',
    CostlyMistakesIntolerance = 'How_do_your_parents_react_against_your_costly_mistakes(breaking_an_expensive_glass)?',
    ParentAcademicDispleasure = 'what_is_reaction_of_your_parents_after_getting_average_academic_record?',
    ParentViolentReactions = 'Have_you_gone_through_Yelling,_hitting,_taunting_(purposefully_or_carelessly)_by_your_parents?',
    UnSupportConfidenceBuilding = 'Have_your_parents_ever_help_you_to_rebuild_your_lost_confidence_by_saying_any_comforting_words?',
    UnAppreciativeParents = 'How_often_does_your_parents_appreciate_you_for_your_achievements?',
    InconsistentScolding = 'Are_there_somethings_which_your_parents_scold_you_on_for_doing,_but_they_do_as_well_(or_have_done_in_past)',
    ClosedCommunication = 'Can_you_easily_discuss_your_critical_matter_with_your_parents?'
  )
mode_gender <- names(which.max(table(data$Gender[data$Gender != "Unspecified"])))

transform_character_values <- function(x) {
  case_when(
    x == "Yes" ~ "No", # Convert "Yes" to "No"
    x == "No" ~ "Yes", # Convert "No" to "Yes"
    TRUE ~ x           # Keep other values unchanged
  )
}
transform_numeric_values <- function(x) {
  case_when(
    x == 1 ~ 5L,       # Convert 1 to 5
    x == 2 ~ 4L,       # Convert 2 to 4
    x == 4 ~ 2L,       # Convert 4 to 2
    x == 5 ~ 1L,       # Convert 5 to 1
    TRUE ~ x           # Keep other values unchanged
  )
}
convert_answers <- function(x) {
  case_when(
    x == "Yes" ~ 5L,    # Convert "Yes" to 5
    x == "yes" ~ 5L,
    x == "Maybe" ~ 3L,  # Convert "Maybe" to 3
    x == "maybe" ~ 3L,
    x == "No" ~ 1L,     # Convert "No" to 1
    x == "no" ~ 1L,
    TRUE ~ NA_integer_  # Keep other values as NA
  )
}
df <- data %>%
  mutate(Gender = ifelse(Gender == "Unspecified", mode_gender, Gender),
         HesitantShareMistakes = transform_character_values(HesitantShareMistakes),
         UnSupportConfidenceBuilding = transform_character_values(UnSupportConfidenceBuilding),
         
         AvoidsNewExperiences = transform_numeric_values(AvoidsNewExperiences),
         LacksSelfConfidence = transform_numeric_values(LacksSelfConfidence),
         LackControlLife = transform_numeric_values(LackControlLife),
         UnAppreciativeParents = transform_numeric_values(UnAppreciativeParents),
         ClosedCommunication = transform_numeric_values(ClosedCommunication),
         CostlyMistakesIntolerance = transform_numeric_values(CostlyMistakesIntolerance),
         HesitantShareMistakes = convert_answers(HesitantShareMistakes),
         UnSupportConfidenceBuilding = convert_answers(UnSupportConfidenceBuilding),
         InconsistentScolding = convert_answers(InconsistentScolding)
         )
```

```{r,echo=TRUE}
self_columns_to_average <- c(
  'PleaseOthers', 'FearOfFailure', 'TroubleInFeedbackReception', 'SelfDoubt', 
  'SelfComparison', 'LackControlLife', 'LacksSelfConfidence', 'AvoidsNewExperiences'
)
parents_columns_to_average <- c(
  'HesitantShareMistakes', 'ParentsSociallyChallenged', 'CostlyMistakesIntolerance', 'ParentAcademicDispleasure', 
  'ParentViolentReactions', 'UnSupportConfidenceBuilding', 'UnAppreciativeParents', 'InconsistentScolding', 'ClosedCommunication'
)

df$AverageSelfQuestions <- rowMeans(df[, self_columns_to_average], na.rm = TRUE)
df$AverageParentsQuestions <- rowMeans(df[, parents_columns_to_average], na.rm = TRUE)
```

```{r,echo=TRUE}
gender_counts <- table(df$Gender)
gender_df <- as.data.frame(gender_counts)
names(gender_df) <- c("Gender", "Count")
pie_chart <- ggplot(gender_df, aes(x = "", y = Count, fill = Gender)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar(theta = "y") +
  scale_fill_manual(values = c("Male" = "skyblue2", "Female" = "plum2")) +
  labs(fill = "Gender",
       title = "Gender Distribution",
       x = NULL,
       y = NULL) +
  theme_minimal() +
  theme(axis.text.x = element_blank(),
        axis.ticks = element_blank(),
        panel.grid = element_blank())
print(pie_chart)
```
```{r,echo=TRUE}
ages_counts <- table(df$AgeGroup)
ages_df <- as.data.frame(ages_counts)
names(ages_df) <- c("AgeGroup", "Count")
pie_chart <- ggplot(ages_df, aes(x = "", y = Count, fill = AgeGroup)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar(theta = "y") +
  scale_fill_manual(values = c("less than 15 years" = "skyblue2", "between 15 and 24 years" = "#B1D7D6","between 25 and 30 years" = "plum", "greater than 30" = "purple3")) +
  labs(fill = "AgeGroup",
       title = "Age Groups Distribution",
       x = NULL,
       y = NULL) +
  theme_minimal() +
  theme(axis.text.x = element_blank(),
        axis.ticks = element_blank(),
        panel.grid = element_blank())
print(pie_chart)
```

```{r,echo=TRUE}
ggplot(df, aes(x = AverageSelfQuestions, y = AverageParentsQuestions)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = "lm", color = "mediumorchid", se = FALSE) +
  labs(x = "Average Self Questions", y = "Average Parents Questions", title = "Correlation between Average Self Questions and Average Parents Questions") +
  theme_minimal()
```

```{r,echo=TRUE}
all_columns <- setdiff(names(df),c("Timestamp","AgeGroup","Gender","AverageSelfQuestions", "AverageParentsQuestions"))
selected_columns <- c("AvoidsNewExperiences", "LacksSelfConfidence", "LackControlLife", 
                      "SelfComparison", "SelfDoubt", "TroubleInFeedbackReception", 
                      "FearOfFailure", "PleaseOthers")

other_columns <- setdiff(all_columns, selected_columns)
cor_matrix <- cor(df[selected_columns], df[other_columns])
melted_cor <- melt(cor_matrix)

ggplot(melted_cor, aes(x = Var2, y = Var1, fill = value)) +
  geom_tile(color = "white", lwd = 0.5, linetype = 1) +
  scale_fill_gradientn(colors = c("#719EF8",  "#9ABBFF", "#C9D7F0", "#E1DAD6","#E8D6CC", "#F2BFA8", "#F7AB8C", "#EF8A6C", "#E26B53", "#C53334", "#B30325"), limits = c(-0.15, 0.30), breaks = seq(-0.1, 0.25, by = 0.05)) +
  geom_text(aes(label = sprintf("%.3f", value)), size = 2.5) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), axis.title.x = element_blank(), axis.title.y = element_blank(), plot.title = element_text(hjust = 0.5, vjust = 1),
        plot.margin = unit(c(0.01, 0.01, 0.01, 0.01), "cm"), legend.key.width = unit(0.3, "cm"), legend.key.height = unit(1, "cm"), legend.title = element_text(size = 10),
        legend.text = element_text(size = 8)) +
  labs(title = "Correlation Self vs. Parents") +
  coord_fixed(ratio = 1)
```

```{r,echo=TRUE}
low_self_esteem_cols <- c('SelfDoubt', 'SelfComparison', 'LacksSelfConfidence')
df$lowSelfEsteem <- rowMeans(df[, low_self_esteem_cols], na.rm = TRUE)
```

```{r,echo=TRUE}
df_self_esteem_one_col_is_5 <- df %>%
  filter(LacksSelfConfidence == 5 | SelfComparison == 5 | SelfDoubt == 5)
```

```{r,echo=TRUE}
dependent_var <- df_self_esteem_one_col_is_5[, 23]
predictor_vars <- df_self_esteem_one_col_is_5[, 12:20]
full_model <- lm(df_self_esteem_one_col_is_5[,23] ~ ., data = df_self_esteem_one_col_is_5[,12:20])
stepwise_model <- step(full_model, direction = "both")
summary(stepwise_model)
```

```{r,echo=TRUE}
ggplot(df_self_esteem_one_col_is_5, aes(x = as.factor(ClosedCommunication), y = lowSelfEsteem)) +
  geom_boxplot(fill = "lightblue", color = "darkblue", outlier.shape = NA, outlier.alpha = 0.2, na.rm = TRUE) +
  geom_jitter(width = 0.1, alpha = 0.4, size = 1) +
  stat_summary(fun = "median", geom = "text", aes(label = round(..y.., 1)), vjust = -1, hjust = -1, size = 3.5, color = "darkblue") +
  theme_minimal() +
  labs(title = "Low Self-Esteem Scores by Closed Communication Levels", 
       x = "Closed Communication Levels",
       y = "Low Self-Esteem Score") +
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(size = 12),
        plot.title = element_text(size = 14, face = "bold"))
```

```{r,echo=TRUE}
df_LacksSelfConfidence_is_5 <- df %>%
  filter(LacksSelfConfidence == 5)

df_SelfComparisone_is_5 <- df %>%
  filter(SelfComparison == 5)

df_SelfDoubt_is_5 <- df %>%
  filter(SelfDoubt == 5)
```

```{r,echo=TRUE}
p1 <- ggplot(df_LacksSelfConfidence_is_5, aes(x = ClosedCommunication)) +
  geom_density(fill = "purple2", alpha = 0.7) +
  labs(x = "", y = "", title = "Lacks Self Confidence is 5") + 
  theme_minimal() + xlim(1, 5) + ylim(0.0, 0.45) +
  theme(plot.title = element_text(size = 10), plot.subtitle = element_text(size = 10))

p2 <- ggplot(df_SelfComparisone_is_5, aes(x = ClosedCommunication)) +
  geom_density(fill = "magenta3", alpha = 0.7) +
  labs(x = "Closed Communication", y = "", title = "Self Comparisone is 5") + 
  theme_minimal() + xlim(1, 5) + ylim(0.0, 0.45) +
  theme(plot.title = element_text(size = 10), plot.subtitle = element_text(size = 10))

p3 <- ggplot(df_SelfDoubt_is_5, aes(x = ClosedCommunication)) +
  geom_density(fill = "violet", alpha = 0.7) +
  labs(x = "", y = "", title = "Self Doubt is 5") + 
  theme_minimal() + xlim(1, 5) + ylim(0.0, 0.45) +
  theme(plot.title = element_text(size = 10), plot.subtitle = element_text(size = 10))

grid.arrange(p1, p2, p3, ncol = 3, top = textGrob("Closed Communication Distribution Across Self-Esteem Attributes", gp = gpar(fontsize = 14, fontface = "bold")))
```
```{r,echo=TRUE}
ggplot(df_LacksSelfConfidence_is_5, aes(x = ClosedCommunication, fill = Gender)) +
  geom_density(alpha = 0.7, size = 0.5) +
  labs(x = "Closed Communication", y = "", title = "Closed Communication by Gender for insecure people", fill = "Gender") +
  scale_fill_manual(values = c("Female" = "hotpink3", "Male" = "seagreen3")) +
  xlim(1,5) +
  theme_minimal() +
  theme(legend.position = "bottom", legend.title = element_blank())
```
```{r,echo=TRUE}
df <- df %>%
  mutate(LacksSelfConfidence_is_5 = ifelse(LacksSelfConfidence == 5, "Insecure Males", "General Male Population"))
cond_male <- df %>% filter(Gender == "Male")
ggplot(cond_male, aes(x = ClosedCommunication, fill = LacksSelfConfidence_is_5)) +
  geom_density(alpha = 0.7, size = 0.5) +
  labs(x = "Closed Communication", y = "", title = "Insecure Males vs. General Male Population: Behavioral Comparison", fill = "") +
  scale_fill_manual(values = c("General Male Population" = "navyblue", "Insecure Males" = "seagreen3")) +
  theme_minimal() +
  theme(legend.position = "bottom", legend.title = element_blank())
```

